Add agentdbg versioning

diff --git a/actions/agentdbg-assert/action.yml b/actions/agentdbg-assert/action.yml
--- a/actions/agentdbg-assert/action.yml
+++ b/actions/agentdbg-assert/action.yml
@@ -1,5 +1,7 @@
 name: 'AgentDbg Assert'
 description: 'Run AgentDbg behavioral regression checks on agent traces'
+env:
+  AGENTDBG_REPO: 'https://github.com/RefineHQ-AI/agentdbg'
 inputs:
   agent-script:
     description: 'Python script that runs the agent (must use @trace)'
@@ -12,6 +14,15 @@ inputs:
     description: 'Path to policy YAML file'
     required: false
     default: '.agentdbg/policy.yaml'
+  agentdbg-version:
+    description: |
+      AgentDbg version to use.
+      Could be a version number starting with 'v' or a branch name starting with '@'.
+      If a github identifier starts with 'v', use '@' prefix.
+      Otherwise PyPI will be used.
+      Default is "@main".
+    required: false
+    default: '@main'
   python-version:
     description: 'Python version to use'
     required: false
@@ -24,6 +35,7 @@ inputs:
     description: 'Post results as PR comment (true/false)'
     required: false
     default: 'true'
+
 runs:
   using: 'composite'
   steps:
@@ -34,7 +46,22 @@ runs:
 
     - name: Install AgentDbg
       shell: bash
-      run: pip install agentdbg
+      run: |
+        if [[ "${{ inputs.agentdbg-version }}" == "@"* ]]; then
+          # GitHub identifier
+          GITHUB_IDENTIFIER="${{ inputs.agentdbg-version:1 }}"
+          pip install git+${{ env.AGENTDBG_REPO }}/${{ GITHUB_IDENTIFIER }}
+        elif [[ "${{ inputs.agentdbg-version }}" == "v"* ]]; then
+          # PyPI version number
+          PYPI_VERSION="${{ inputs.agentdbg-version:1 }}"
+          pip install "agentdbg==${{ PYPI_VERSION }}"
+        else
+          # Let's not allow any other values
+          echo "Invalid agentdbg-version: ${{ inputs.agentdbg-version }}."
+          echo "AgentDbg version must start with 'v' for PyPI version number"
+          echo "or '@' for GitHub identifier."
+          exit 1
+        fi
 
     - name: Run agent
       shell: bash
